import type { Metadata } from "next";
import Image from "next/image";
import { Heart } from "lucide-react";
import { notFound } from "next/navigation";
import { CollectiveRsvpForm } from "@/components/invitations/collective-rsvp-form";
import { prisma } from "@/lib/prisma";

type Props={params:Promise<{weddingSlug:string;token:string}>};
export const metadata:Metadata={title:"Confirmation de présence — Noces",robots:{index:false,follow:false}};
export default async function CollectiveRsvpPage({params}:Props){const{weddingSlug,token}=await params;if(token.length<32||token.length>96)notFound();const wedding=await prisma.wedding.findFirst({where:{slug:weddingSlug,publicRsvpToken:token,publicRsvpEnabled:true,status:"ACTIVE"},select:{partnerOne:true,partnerTwo:true,weddingDate:true,rsvpDeadline:true,city:true,coverImageUrl:true,publicRsvpMaxGuests:true}});if(!wedding)notFound();return <main className="min-h-screen bg-[#f8f3eb] text-[#49372f]"><section className="relative overflow-hidden bg-[#49372f] px-5 py-16 text-center text-white">{wedding.coverImageUrl&&<Image src={wedding.coverImageUrl} alt="" fill priority sizes="100vw" className="object-cover opacity-25"/>}<div className="relative mx-auto max-w-4xl"><Heart className="mx-auto text-[#f19a9a]" fill="currentColor"/><p className="mt-5 text-xs uppercase tracking-[.3em] text-white/65">Confirmation ouverte</p><h1 className="serif mt-5 text-6xl sm:text-7xl">{wedding.partnerOne} <em className="text-[#f19a9a]">&</em> {wedding.partnerTwo}</h1><p className="mt-5 text-sm text-white/70">{new Intl.DateTimeFormat("fr-FR",{dateStyle:"long",timeZone:"Africa/Abidjan"}).format(wedding.weddingDate)}{wedding.city?` · ${wedding.city}`:""}</p></div></section><section className="mx-auto grid max-w-6xl gap-12 px-5 py-16 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div><p className="eyebrow">Vous êtes invité</p><h2 className="serif mt-4 text-5xl">Dites-nous simplement si vous serez des nôtres.</h2><p className="mt-6 leading-8 text-[#715b50]">Ce formulaire peut être partagé avec toute votre famille et vos proches. Chaque réponse est ajoutée automatiquement à la liste des mariés.</p>{wedding.rsvpDeadline&&<p className="mt-6 border-l-2 border-[var(--caramel)] pl-4 text-sm">Réponse souhaitée avant le {new Intl.DateTimeFormat("fr-FR",{dateStyle:"long",timeZone:"Africa/Abidjan"}).format(wedding.rsvpDeadline)}</p>}</div><CollectiveRsvpForm weddingSlug={weddingSlug} token={token} maxGuests={wedding.publicRsvpMaxGuests}/></section></main>}
