import Image from "next/image";
import { BookHeart, Images, ShieldCheck } from "lucide-react";
import type { ModerationStatus } from "@prisma/client";
import { ModerationButtons } from "@/components/memories/moderation-buttons";
import { getMemoryDashboard } from "@/features/memories/memory-data";
import { getCurrentMembership } from "@/server/auth/authorization";
const statuses=["PENDING","APPROVED","REJECTED"] as const;const labels={PENDING:"En attente",APPROVED:"Approuvés",REJECTED:"Refusés"};
export default async function MemoriesPage({searchParams}:{searchParams:Promise<{status?:string}>}){const membership=await getCurrentMembership();if(!membership)return null;const params=await searchParams;const status=statuses.includes(params.status as ModerationStatus)?params.status as ModerationStatus:undefined;const data=await getMemoryDashboard(membership.weddingId,status);const canEdit=["OWNER","ADMIN","ORGANIZER"].includes(membership.role);return <div className="mx-auto max-w-7xl"><div><p className="eyebrow">Souvenirs partagés</p><h1 className="serif mt-2 text-4xl sm:text-5xl">Galerie & livre d’or</h1><p className="mt-3 text-sm text-[var(--caramel)]">Validez les photos et les messages avant leur publication sur les invitations.</p></div><section className="mt-8 grid gap-4 sm:grid-cols-3"><Stat icon={ShieldCheck} label="En attente" value={data.counts.PENDING}/><Stat icon={Images} label="Approuvés" value={data.counts.APPROVED}/><Stat icon={BookHeart} label="Refusés" value={data.counts.REJECTED}/></section><div className="mt-6 flex gap-2 overflow-auto">{[{value:undefined,label:"Tous"},...statuses.map(value=>({value,label:labels[value]}))].map(tab=><a key={tab.label} href={tab.value?`/dashboard/memories?status=${tab.value}`:"/dashboard/memories"} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${status===tab.value?"bg-[var(--brown)] text-white":"border border-[var(--beige)] bg-white"}`}>{tab.label}</a>)}</div>
  <section className="mt-8"><h2 className="serif text-3xl">Photos ({data.photos.length})</h2><div className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.photos.map(photo=><article key={photo.id} className="overflow-hidden rounded-2xl border border-[var(--beige)] bg-white"><div className="relative aspect-square"><Image src={photo.imageUrl} alt={photo.caption??`Photo de ${photo.guest.firstName}`} fill sizes="(max-width:640px) 100vw, (max-width:1024px) 50vw, 33vw" className="object-cover"/></div><div className="p-4"><p className="font-semibold">{photo.guest.firstName} {photo.guest.lastName}</p><p className="mt-1 text-xs text-[var(--caramel)]">{labels[photo.status]} · {new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium"}).format(new Date(photo.createdAt))}</p>{photo.caption&&<p className="mt-3 text-sm">{photo.caption}</p>}{canEdit&&<div className="mt-4"><ModerationButtons id={photo.id} kind="photo" status={photo.status}/></div>}</div></article>)}</div>{!data.photos.length&&<Empty/>}</section>
  <section className="mt-10"><h2 className="serif text-3xl">Livre d’or ({data.entries.length})</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{data.entries.map(entry=><article key={entry.id} className="rounded-2xl border border-[var(--beige)] bg-white p-5"><p className="text-sm leading-7">“{entry.message}”</p><div className="mt-5 border-t border-[var(--beige)] pt-4"><p className="font-semibold">{entry.guest.firstName} {entry.guest.lastName}</p><p className="mt-1 text-xs text-[var(--caramel)]">{labels[entry.status]}</p>{canEdit&&<div className="mt-4"><ModerationButtons id={entry.id} kind="entry" status={entry.status}/></div>}</div></article>)}</div>{!data.entries.length&&<Empty/>}</section></div>}
function Stat({icon:Icon,label,value}:{icon:typeof Images;label:string;value:number}){return <article className="rounded-2xl border border-[var(--beige)] bg-white p-5"><div className="flex justify-between"><p className="text-xs text-[var(--caramel)]">{label}</p><Icon size={17}/></div><p className="serif mt-5 text-4xl">{value}</p></article>}function Empty(){return <p className="mt-4 rounded-2xl border border-dashed border-[var(--taupe)] p-8 text-center text-sm text-[var(--caramel)]">Aucun souvenir dans cette section.</p>}
