"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { GripVertical, UserRound } from "lucide-react";
import { assignGuestAction } from "@/app/dashboard/tables/actions";
import { DeleteTableButton } from "@/components/tables/delete-table-button";
import { TableFormDialog } from "@/components/tables/table-form-dialog";

type Guest = { id:string;firstName:string;lastName:string;group:{name:string}|null;rsvp:{guestCount:number}|null };
type Table = { id:string;name:string;number:number|null;capacity:number;description:string|null;assignments:Array<{id:string;seats:number;guest:Guest}> };

export function TablePlanner({tables,unassigned,canEdit}:{tables:Table[];unassigned:Guest[];canEdit:boolean}) {
  const router=useRouter(); const [pending,startTransition]=useTransition(); const [error,setError]=useState(""); const [dragOver,setDragOver]=useState<string|null>(null);
  const allGuests=[...unassigned,...tables.flatMap((table)=>table.assignments.map((assignment)=>assignment.guest))];
  function move(guestId:string,tableId:string|null) { setError(""); startTransition(async()=>{let result=await assignGuestAction({guestId,tableId});if(result.requiresConfirmation){const confirmed=window.confirm(`Cette attribution occupera ${result.projected} places sur ${result.capacity}. Confirmer le dépassement ?`);if(confirmed)result=await assignGuestAction({guestId,tableId,force:true});}if(!result.ok&&!result.requiresConfirmation)setError(result.error??"Déplacement impossible");router.refresh();}); }
  function drop(event:React.DragEvent,tableId:string|null){event.preventDefault();setDragOver(null);const guestId=event.dataTransfer.getData("text/guest-id");if(guestId)move(guestId,tableId);}
  return <div className={pending?"opacity-70":""}>{error&&<p className="mb-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>drop(event,null)} className={`rounded-2xl border-2 border-dashed p-5 transition ${dragOver==="unassigned"?"border-[var(--gold)] bg-white":"border-[var(--taupe)]/50 bg-white/45"}`} onDragEnter={()=>setDragOver("unassigned")}><div className="flex items-center justify-between"><div><p className="eyebrow">À placer</p><h2 className="serif mt-1 text-3xl">Invités non attribués</h2></div><span className="rounded-full bg-[var(--brown)] px-3 py-1 text-xs text-white">{unassigned.length}</span></div><div className="mt-5 flex min-h-16 flex-wrap gap-3">{unassigned.length?unassigned.map((guest)=><GuestCard key={guest.id} guest={guest} tables={tables} tableId={null} canEdit={canEdit} onMove={move}/>):<p className="self-center text-sm text-[var(--caramel)]">Tous les invités confirmés sont placés.</p>}</div></section>
    <section className="mt-6 grid gap-5 xl:grid-cols-2">{tables.map((table)=>{const occupied=table.assignments.reduce((sum,item)=>sum+item.seats,0);const full=occupied>=table.capacity;return <article key={table.id} onDragOver={(event)=>event.preventDefault()} onDragEnter={()=>setDragOver(table.id)} onDragLeave={()=>setDragOver(null)} onDrop={(event)=>drop(event,table.id)} className={`rounded-3xl border-2 bg-white p-5 transition ${dragOver===table.id?"border-[var(--gold)]":"border-[var(--beige)]"}`}><header className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="serif text-3xl">{table.name}</h2>{table.number&&<span className="text-xs text-[var(--caramel)]">N° {table.number}</span>}</div><p className={`mt-2 text-sm ${occupied>table.capacity?"font-semibold text-red-700":full?"text-amber-700":"text-[var(--caramel)]"}`}>{occupied} / {table.capacity} places{occupied>table.capacity?" · Capacité dépassée":full?" · Table complète":""}</p>{table.description&&<p className="mt-1 text-xs text-[var(--caramel)]">{table.description}</p>}</div>{canEdit&&<div className="flex"><TableFormDialog table={table}/><DeleteTableButton id={table.id} name={table.name}/></div>}</header><div className="mt-5 h-2 overflow-hidden rounded-full bg-[var(--ivory)]"><div className={`h-full rounded-full ${occupied>table.capacity?"bg-red-600":full?"bg-amber-500":"bg-[var(--brown)]"}`} style={{width:`${Math.min(100,occupied/table.capacity*100)}%`}}/></div><div className="mt-5 min-h-24 space-y-2">{table.assignments.length?table.assignments.map((assignment)=><GuestCard key={assignment.id} guest={assignment.guest} tables={tables} tableId={table.id} canEdit={canEdit} onMove={move}/>):<p className="grid min-h-20 place-items-center rounded-xl border border-dashed border-[var(--beige)] text-xs text-[var(--caramel)]">Déposez un invité ici</p>}</div></article>})}</section>
    {tables.length===0&&<div className="mt-6 grid min-h-72 place-items-center rounded-2xl border border-dashed border-[var(--taupe)] bg-white/50 text-center"><div><UserRound className="mx-auto text-[var(--taupe)]"/><h2 className="serif mt-4 text-3xl">Créez votre première table</h2><p className="mt-2 text-sm text-[var(--caramel)]">Vous pourrez ensuite y déposer les invités confirmés.</p></div></div>}
    <span className="sr-only">{allGuests.length} invités disponibles</span></div>;
}

function GuestCard({guest,tables,tableId,canEdit,onMove}:{guest:Guest;tables:Table[];tableId:string|null;canEdit:boolean;onMove:(guestId:string,tableId:string|null)=>void}) {const seats=guest.rsvp?.guestCount??0;return <div draggable={canEdit} onDragStart={(event)=>{event.dataTransfer.setData("text/guest-id",guest.id);event.dataTransfer.effectAllowed="move";}} className="flex min-w-56 items-center gap-3 rounded-xl border border-[var(--beige)] bg-[var(--ivory)] p-3"><GripVertical className={canEdit?"cursor-grab text-[var(--taupe)]":"text-[var(--beige)]"} size={17}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{guest.firstName} {guest.lastName}</p><p className="text-xs text-[var(--caramel)]">{seats} place{seats>1?"s":""}{guest.group?` · ${guest.group.name}`:""}</p></div>{canEdit&&<select aria-label={`Table de ${guest.firstName}`} value={tableId??""} onChange={(event)=>onMove(guest.id,event.target.value||null)} className="max-w-28 rounded-lg border border-[var(--beige)] bg-white px-2 py-1.5 text-xs"><option value="">À placer</option>{tables.map((table)=><option key={table.id} value={table.id}>{table.name}</option>)}</select>}</div>;}
