"use client";

import { Check, Heart, Users, X } from "lucide-react";
import { useActionState, useState } from "react";
import { submitCollectiveRsvpAction,type CollectiveRsvpState } from "@/app/w/[weddingSlug]/rsvp/[token]/actions";

export function CollectiveRsvpForm({weddingSlug,token,maxGuests}:{weddingSlug:string;token:string;maxGuests:number}){
  const[state,action,pending]=useActionState<CollectiveRsvpState,FormData>(submitCollectiveRsvpAction,{});
  const[status,setStatus]=useState<"CONFIRMED"|"DECLINED"|null>(null);
  const[count,setCount]=useState(1);
  if(state.ok)return <div className="bg-white p-8 text-center shadow-2xl"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check/></span><h2 className="serif mt-6 text-4xl">Merci {state.guestName} !</h2><p className="mt-4 text-sm leading-7 text-[#715b50]">Votre réponse est enregistrée et apparaît maintenant dans le tableau de bord des mariés.</p></div>;
  return <form action={action} className="bg-white p-6 text-left shadow-2xl sm:p-9"><input type="hidden" name="weddingSlug" value={weddingSlug}/><input type="hidden" name="token" value={token}/><input type="hidden" name="status" value={status??""}/><label className="absolute -left-[9999px]" aria-hidden="true">Votre site<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="eyebrow">Votre réponse</p><h2 className="serif mt-3 text-4xl">Qui êtes-vous ?</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field name="firstName" label="Prénom" required/><Field name="lastName" label="Nom" required/><Field name="email" label="E-mail" type="email"/><Field name="phone" label="Téléphone / WhatsApp" type="tel"/></div><p className="mt-3 text-xs text-[#9b7258]">Indiquez au moins un e-mail ou un téléphone.</p>
    <h3 className="serif mt-8 text-3xl">Serez-vous présent ?</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setStatus("CONFIRMED")} className={`border-2 p-5 text-left ${status==="CONFIRMED"?"border-emerald-600 bg-emerald-50":"border-[#e7d9c8]"}`}><Heart size={19}/><strong className="mt-3 block">Oui, avec plaisir</strong></button><button type="button" onClick={()=>setStatus("DECLINED")} className={`border-2 p-5 text-left ${status==="DECLINED"?"border-[var(--caramel)] bg-[#f8f3eb]":"border-[#e7d9c8]"}`}><X size={19}/><strong className="mt-3 block">Non, malheureusement</strong></button></div>
    {status==="CONFIRMED"&&<div className="mt-7 border-t border-[#e7d9c8] pt-7"><label className="text-sm font-semibold"><span className="flex items-center gap-2"><Users size={16}/>Nombre de personnes</span><select name="guestCount" value={count} onChange={event=>setCount(Number(event.target.value))} className="mt-2 w-full border border-[#e7d9c8] bg-white px-4 py-3">{Array.from({length:maxGuests},(_,index)=>index+1).map(value=><option key={value}>{value}</option>)}</select></label>{count>1&&<div className="mt-5 space-y-3"><p className="text-sm font-semibold">Accompagnateurs</p>{Array.from({length:count-1},(_,index)=><input key={index} required name="companions" placeholder={`Nom de l’accompagnateur ${index+1}`} className="w-full border border-[#e7d9c8] px-4 py-3"/>)}</div>}<label className="mt-5 block text-sm font-semibold">Nombre d’enfants<select name="childrenCount" defaultValue="0" className="mt-2 w-full border border-[#e7d9c8] bg-white px-4 py-3">{Array.from({length:count+1},(_,index)=>index).map(value=><option key={value}>{value}</option>)}</select></label></div>}
    {status&&<label className="mt-6 block text-sm font-semibold">Un mot pour les mariés<textarea name="message" rows={3} maxLength={1000} className="mt-2 w-full border border-[#e7d9c8] px-4 py-3"/></label>}{state.error&&<p role="alert" className="mt-5 bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}<button disabled={pending||!status} className="button-primary mt-7 w-full disabled:opacity-40">{pending?"Enregistrement…":"Envoyer ma réponse"}</button>
  </form>;
}
function Field({name,label,type="text",required=false}:{name:string;label:string;type?:string;required?:boolean}){return <label className="text-sm font-semibold">{label}<input name={name} type={type} required={required} className="mt-2 w-full border border-[#e7d9c8] px-4 py-3"/></label>}
