ALTER TABLE `User` ADD COLUMN `status` ENUM('ACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `Wedding`
  ADD COLUMN `status` ENUM('ACTIVE', 'SUSPENDED', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN `plan` ENUM('FREE', 'ESSENTIAL', 'PREMIUM') NOT NULL DEFAULT 'FREE',
  ADD COLUMN `accentColor` VARCHAR(191) NOT NULL DEFAULT 'caramel',
  ADD COLUMN `siteLayout` VARCHAR(191) NOT NULL DEFAULT 'editorial';
