"use client";
import { Headphones, Pencil, Trash2, X } from "lucide-react";
import { useRef } from "react";
import { deleteWeddingAction, editWeddingAction, startSupportSessionAction, updateWeddingAction } from "@/app/admin/actions";
import { DesignPicker } from "@/components/settings/design-picker";
type Wedding={id:string;slug:string;partnerOne:string;partnerTwo:string;weddingDate:string;city:string|null;country:string|null;status:"ACTIVE"|"SUSPENDED"|"ARCHIVED";plan:"FREE"|"ESSENTIAL"|"PREMIUM";theme:string;accentColor:string;siteLayout:string;guestCount:number;owner:string};
const statuses=["ACTIVE","SUSPENDED","ARCHIVED"] as const,plans=["FREE","ESSENTIAL","PREMIUM"] as const;
export function WeddingCrudCard({wedding}:{wedding:Wedding}){const edit=useRef<HTMLDialogElement>(null),remove=useRef<HTMLDialogElement>(null),support=useRef<HTMLDialogElement>(null);return <article className="border border-[var(--beige)] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="serif text-2xl">{wedding.partnerOne} & {wedding.partnerTwo}</h2><p className="text-xs text-[var(--caramel)]">/{wedding.slug} · {wedding.city||"Ville non renseignée"} · {wedding.guestCount} invités</p><p className="mt-2 text-xs text-[#777]">Propriétaire : {wedding.owner}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>support.current?.showModal()} className="button-primary !py-2 text-xs"><Headphones size={14}/>Assistance</button><button onClick={()=>edit.current?.showModal()} className="button-secondary !py-2 text-xs"><Pencil size={14}/>Modifier</button><button onClick={()=>remove.current?.showModal()} className="button-secondary !py-2 text-xs text-red-700"><Trash2 size={14}/>Supprimer</button></div></div><form action={updateWeddingAction} className="mt-5 grid gap-4 border-t border-[var(--beige)] pt-4 md:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="weddingId" value={wedding.id}/><Choice name="status" label="État du compte" values={statuses} current={wedding.status}/><Choice name="plan" label="Abonnement" values={plans} current={wedding.plan}/><button className="button-secondary self-end !py-2 text-xs">Enregistrer</button></form>
<dialog ref={support} className="m-auto w-[min(92vw,520px)] border border-[var(--beige)] bg-white p-7 shadow-2xl backdrop:bg-black/50"><div className="flex justify-between"><div><p className="eyebrow">Accès audité</p><h3 className="serif mt-2 text-3xl">Démarrer une assistance</h3></div><button onClick={()=>support.current?.close()}><X/></button></div><p className="mt-3 text-sm leading-6 text-[#777]">L’accès est limité à ce mariage, expire automatiquement et apparaît dans le journal.</p><form action={startSupportSessionAction} className="mt-6 space-y-4"><input type="hidden" name="weddingId" value={wedding.id}/><label className="block text-sm">Motif<textarea required minLength={5} maxLength={500} name="reason" rows={3} className="admin-input mt-2" placeholder="Ex. Assistance à la configuration du mini-site"/></label><label className="block text-sm">Durée<select name="duration" className="admin-input mt-2"><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">1 heure</option></select></label><button className="button-primary w-full">Démarrer la session</button></form></dialog>
<dialog ref={edit} className="m-auto w-[min(94vw,850px)] border border-[var(--beige)] bg-white p-0 shadow-2xl backdrop:bg-black/50"><form action={editWeddingAction} className="p-6 sm:p-8"><div className="flex justify-between"><h3 className="serif text-3xl">Modifier le mariage</h3><button type="button" onClick={()=>edit.current?.close()}><X/></button></div><input type="hidden" name="weddingId" value={wedding.id}/><div className="mt-6 grid gap-3 sm:grid-cols-2"><Input name="partnerOne" label="Premier marié" value={wedding.partnerOne}/><Input name="partnerTwo" label="Deuxième marié" value={wedding.partnerTwo}/><Input name="weddingDate" label="Date" type="datetime-local" value={wedding.weddingDate}/><Input name="city" label="Ville" value={wedding.city??""}/><Input name="country" label="Pays" value={wedding.country??""}/></div><DesignPicker className="mt-7" defaults={wedding}/><button className="button-primary mt-7 w-full">Enregistrer</button></form></dialog>
<dialog ref={remove} className="m-auto w-[min(92vw,480px)] border border-red-200 bg-white p-7 shadow-2xl backdrop:bg-black/50"><h3 className="serif text-3xl">Supprimer cet espace ?</h3><p className="mt-3 text-sm text-[#777]">Cette action est irréversible.</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>remove.current?.close()} className="button-secondary">Annuler</button><form action={deleteWeddingAction}><input type="hidden" name="weddingId" value={wedding.id}/><button className="bg-red-700 px-5 py-3 text-sm text-white">Supprimer définitivement</button></form></div></dialog></article>}
function Choice({name,label,values,current}:{name:string;label:string;values:readonly string[];current:string}){return <fieldset><legend className="text-[10px] uppercase tracking-wider text-[var(--caramel)]">{label}</legend><div className="mt-2 flex flex-wrap gap-2">{values.map(value=><label key={value}><input className="peer sr-only" type="radio" name={name} value={value} defaultChecked={current===value}/><span className="block cursor-pointer border px-3 py-2 text-xs peer-checked:border-[var(--caramel)] peer-checked:bg-[var(--reference-blush)]">{value}</span></label>)}</div></fieldset>}
function Input({name,label,value,type="text"}:{name:string;label:string;value:string;type?:string}){return <label className="text-xs">{label}<input required name={name} type={type} defaultValue={value} className="admin-input mt-1"/></label>}
