import type { Metadata } from "next";
import Image from "next/image";
import { BookHeart, CalendarPlus, Clock3, Heart, Images, MapPin, Navigation, Phone, Shirt } from "lucide-react";
import { notFound } from "next/navigation";
import { Countdown } from "@/components/invitations/countdown";
import { OpenTracker } from "@/components/invitations/open-tracker";
import { RsvpForm } from "@/components/invitations/rsvp-form";
import { MemoryContributionForm } from "@/components/invitations/memory-contribution-form";
import { getPublicInvitation } from "@/features/invitations/public-invitation";
import type { CSSProperties } from "react";

type Props = { params: Promise<{ weddingSlug: string; token: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { weddingSlug, token } = await params;
  const invitation = await getPublicInvitation(weddingSlug, token);
  if (!invitation) return { title: "Invitation introuvable — Noces", robots: { index: false, follow: false } };
  const wedding = invitation.guest.wedding;
  return {
    title: `${wedding.partnerOne} & ${wedding.partnerTwo} — Invitation de mariage`,
    description: `Vous êtes invité au mariage de ${wedding.partnerOne} et ${wedding.partnerTwo}.`,
    robots: { index: false, follow: false },
  };
}

export default async function InvitationPage({ params }: Props) {
  const { weddingSlug, token } = await params;
  const invitation = await getPublicInvitation(weddingSlug, token);
  if (!invitation) notFound();
  const { guest } = invitation;
  const wedding = guest.wedding;
  const date = new Intl.DateTimeFormat("fr-FR", { dateStyle: "full", timeStyle: "short", timeZone: "Africa/Abidjan" }).format(wedding.weddingDate);
  const shortDate = new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "long", year: "numeric", timeZone: "Africa/Abidjan" }).format(wedding.weddingDate);
  const accents:Record<string,string>={coral:"#e35d5d",caramel:"#9b7258",rose:"#a86370",sage:"#70836b",navy:"#34455c",gold:"#b79a45",terracotta:"#b8664b",lavender:"#76658a",emerald:"#285943"};
  const siteStyle={"--site-accent":accents[wedding.accentColor]??accents.caramel} as CSSProperties;
  const layoutClass=`site-${["minimal","cinematic","classic","split"].includes(wedding.siteLayout)?wedding.siteLayout:"editorial"}`;
  const configured=wedding.siteSections&&typeof wedding.siteSections==="object"&&!Array.isArray(wedding.siteSections)?wedding.siteSections as Record<string,boolean>:{};
  const visible=(section:string)=>configured[section]!==false;

  return <main style={siteStyle} className={`overflow-hidden bg-[#f8f3eb] text-[#49372f] ${layoutClass}`}><OpenTracker token={token}/>
    <section className="relative grid min-h-[92vh] place-items-center overflow-hidden bg-[#49372f] px-5 py-20 text-center text-white">
      {wedding.coverImageUrl && <Image src={wedding.coverImageUrl} alt={`${wedding.partnerOne} et ${wedding.partnerTwo}`} fill priority sizes="100vw" className="object-cover opacity-25"/>}
      <div className="absolute -left-32 -top-32 h-96 w-96 rounded-full border border-white/10"/><div className="absolute -bottom-44 -right-24 h-[520px] w-[520px] rounded-full bg-[#b99d88]/15"/><div className="absolute left-[10%] top-24 hidden h-52 w-40 -rotate-6 rounded-t-full border border-white/15 lg:block"/><div className="absolute bottom-20 right-[9%] hidden h-56 w-44 rotate-6 rounded-t-full bg-[#b99d88]/15 lg:block"/>
      <div className="relative z-10 mx-auto max-w-4xl"><p className="text-xs uppercase tracking-[.35em] text-[#e7d9c8]">{wedding.heroEyebrow||"Une invitation rien que pour vous"}</p><p className="serif mt-8 text-2xl italic text-white/70">Cher{guest.firstName.endsWith("e") ? "e" : ""} {guest.firstName},</p><h1 className="serif mt-8 text-7xl font-medium leading-[.78] tracking-[-.04em] sm:text-8xl lg:text-[9rem]">{wedding.partnerOne}<span className="block text-5xl italic text-[#d5b770] sm:text-7xl">&</span>{wedding.partnerTwo}</h1><p className="mx-auto mt-10 max-w-xl text-sm uppercase leading-7 tracking-[.2em] text-white/70">ont l’immense joie de vous inviter à célébrer leur mariage</p><div className="mx-auto mt-10 h-px w-28 bg-[#d5b770]"/><p className="serif mt-8 text-3xl capitalize sm:text-4xl">{shortDate}</p><p className="mt-3 text-xs uppercase tracking-[.25em] text-white/55">{wedding.city}{wedding.country ? ` · ${wedding.country}` : ""}</p></div>
    </section>

    <section className="bg-[var(--site-accent)] px-4 py-16 text-white sm:px-8"><div className="mx-auto max-w-4xl"><p className="mb-8 text-center text-xs uppercase tracking-[.3em] text-white/70">Notre mariage commence dans</p><Countdown target={wedding.weddingDate.toISOString()}/></div></section>

    {visible("story")&&<section className="paper px-5 py-24 text-center"><div className="mx-auto max-w-3xl"><Heart className="mx-auto text-[#b79a45]" fill="currentColor" size={24}/><p className="eyebrow mt-7">Notre histoire</p><h2 className="serif mt-4 text-5xl sm:text-6xl">{wedding.storyTitle||"Nous serions heureux de vous compter parmi nous."}</h2><p className="mx-auto mt-8 max-w-2xl whitespace-pre-line text-base leading-8 text-[#715b50]">{wedding.storyText||wedding.message||`Entourés de nos familles et de ceux qui nous sont chers, nous avons choisi de nous dire oui. Votre présence rendra cette journée encore plus précieuse.`}</p><div className="mt-10 inline-flex items-center gap-2 rounded-full border border-[#e7d9c8] bg-white px-5 py-3 text-sm"><CalendarPlus size={17}/><a href={`/api/invitations/${token}/calendar`}>Ajouter à mon calendrier</a></div></div></section>}
    {(wedding.partnerOneImageUrl||wedding.partnerTwoImageUrl)&&<section className="bg-white px-5 py-24"><div className="mx-auto grid max-w-4xl gap-6 sm:grid-cols-2">{wedding.partnerOneImageUrl&&<Portrait src={wedding.partnerOneImageUrl} name={wedding.partnerOne}/>} {wedding.partnerTwoImageUrl&&<Portrait src={wedding.partnerTwoImageUrl} name={wedding.partnerTwo}/>}</div></section>}

    <section className="bg-white px-5 py-24"><div className="mx-auto max-w-5xl"><div className="text-center"><p className="eyebrow">Le grand jour</p><h2 className="serif mt-4 text-5xl sm:text-6xl">Rendez-vous le {shortDate}</h2><p className="mt-4 flex items-center justify-center gap-2 text-sm text-[#9b7258]"><Clock3 size={16}/>{date}</p></div>{wedding.venues.length ? <div className="mt-14 grid gap-5 md:grid-cols-2">{wedding.venues.map((venue)=><article key={venue.id} className="rounded-[2rem] border border-[#e7d9c8] bg-[#f8f3eb] p-7"><MapPin className="text-[#b79a45]"/><p className="mt-7 text-xs uppercase tracking-[.2em] text-[#9b7258]">{venue.type === "CEREMONY" ? "Cérémonie" : venue.type === "RECEPTION" ? "Réception" : "Lieu"}</p><h3 className="serif mt-2 text-3xl">{venue.name}</h3><p className="mt-3 text-sm leading-6 text-[#715b50]">{venue.address}{venue.city ? `, ${venue.city}` : ""}</p>{venue.mapsUrl && <a className="button-primary mt-6 text-sm" href={venue.mapsUrl} target="_blank" rel="noreferrer"><Navigation size={15}/> Voir l’itinéraire</a>}</article>)}</div> : <div className="mx-auto mt-12 max-w-xl rounded-3xl border border-[#e7d9c8] bg-[#f8f3eb] p-8 text-center"><MapPin className="mx-auto text-[#b79a45]"/><p className="serif mt-4 text-2xl">{wedding.city}{wedding.country ? `, ${wedding.country}` : ""}</p><p className="mt-2 text-sm text-[#9b7258]">Les détails du lieu seront communiqués prochainement.</p></div>}</div></section>

    {(wedding.schedule.length > 0 || wedding.dressCode) && <section className="paper px-5 py-24"><div className="mx-auto grid max-w-5xl gap-16 lg:grid-cols-2">{wedding.schedule.length>0 && <div><p className="eyebrow">Programme</p><h2 className="serif mt-3 text-5xl">Les temps forts</h2><div className="mt-10 space-y-6">{wedding.schedule.map((item)=><div key={item.id} className="grid grid-cols-[90px_1fr] items-center border-b border-[#e7d9c8] pb-5"><p className="serif text-2xl text-[#9b7258]">{new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit",timeZone:"Africa/Abidjan"}).format(item.startsAt)}</p><p className="serif text-2xl">{item.title}</p></div>)}</div></div>}{wedding.dressCode && <div className="rounded-[2rem] bg-[#49372f] p-9 text-white"><Shirt className="text-[#d5b770]"/><p className="mt-10 text-xs uppercase tracking-[.25em] text-white/60">Dress code</p><h2 className="serif mt-3 text-5xl">{wedding.dressCode}</h2><p className="mt-5 text-sm leading-7 text-white/65">Merci de respecter cet univers pour rendre notre célébration encore plus harmonieuse.</p></div>}</div></section>}

    <section id="rsvp" className="bg-[#49372f] px-5 py-24 text-center text-white"><div className="mx-auto max-w-3xl"><p className="text-xs uppercase tracking-[.3em] text-[#e7d9c8]">Votre invitation</p><h2 className="serif mt-5 text-5xl sm:text-6xl">Une place vous est réservée.</h2><p className="mx-auto mt-6 max-w-lg text-sm leading-7 text-white/65">Cette invitation autorise jusqu’à <strong className="text-white">{guest.maxGuests} personne{guest.maxGuests>1?"s":""}</strong>.</p>{wedding.rsvpDeadline && <p className="mt-5 text-xs uppercase tracking-[.18em] text-[#d5b770]">Réponse souhaitée avant le {new Intl.DateTimeFormat("fr-FR",{dateStyle:"long",timeZone:"Africa/Abidjan"}).format(wedding.rsvpDeadline)}</p>}<div className="mt-10"><RsvpForm weddingSlug={wedding.slug} token={token} firstName={guest.firstName} maxGuests={guest.maxGuests} initialRsvp={guest.rsvp ? { status: guest.rsvp.status as "CONFIRMED" | "DECLINED", guestCount: guest.rsvp.guestCount, childrenCount: guest.rsvp.childrenCount, contactPhone: guest.rsvp.contactPhone, message: guest.rsvp.message, companions: guest.companions.map((companion)=>companion.name) } : null}/></div>{wedding.contactPhone && <a className="mt-9 inline-flex items-center gap-2 text-sm text-white/70 underline" href={`tel:${wedding.contactPhone}`}><Phone size={16}/> Contacter les mariés</a>}</div></section>
    <section className="paper px-5 py-24"><div className="mx-auto max-w-6xl text-center"><Images className="mx-auto text-[#b79a45]"/><p className="eyebrow mt-5">Album partagé</p><h2 className="serif mt-4 text-5xl sm:text-6xl">Nos souvenirs en images</h2>{wedding.galleryPhotos.length?<div className="mt-12 columns-1 gap-4 sm:columns-2 lg:columns-3">{wedding.galleryPhotos.map(photo=><figure key={photo.id} className="mb-4 break-inside-avoid overflow-hidden rounded-2xl bg-white"><Image src={photo.imageUrl} alt={photo.caption??`Souvenir partagé par ${photo.guest.firstName}`} width={photo.width} height={photo.height} sizes="(max-width:640px) 100vw, (max-width:1024px) 50vw, 33vw" className="h-auto w-full"/><figcaption className="p-4 text-left text-sm"><p>{photo.caption??"Un joli souvenir partagé"}</p><p className="mt-1 text-xs text-[#9b7258]">— {photo.guest.firstName}</p></figcaption></figure>)}</div>:<p className="mx-auto mt-8 max-w-lg text-sm text-[#9b7258]">La galerie attend ses premiers souvenirs.</p>}</div></section>
    <section className="bg-white px-5 py-24"><div className="mx-auto max-w-5xl text-center"><BookHeart className="mx-auto text-[#b79a45]"/><p className="eyebrow mt-5">Livre d’or</p><h2 className="serif mt-4 text-5xl sm:text-6xl">Vos mots nous accompagnent</h2>{wedding.guestBookEntries.length?<div className="mt-12 grid gap-5 md:grid-cols-2">{wedding.guestBookEntries.map(entry=><blockquote key={entry.id} className="rounded-[2rem] border border-[#e7d9c8] bg-[#f8f3eb] p-7 text-left"><p className="serif text-2xl leading-9">“{entry.message}”</p><footer className="mt-5 text-xs uppercase tracking-[.16em] text-[#9b7258]">{entry.guest.firstName}</footer></blockquote>)}</div>:<p className="mx-auto mt-8 max-w-lg text-sm text-[#9b7258]">Soyez parmi les premiers à laisser un petit mot.</p>}<MemoryContributionForm weddingSlug={wedding.slug} token={token}/></div></section>
    <footer className="paper px-5 py-12 text-center"><p className="serif text-3xl">{wedding.partnerOne} <span className="italic text-[#b79a45]">&</span> {wedding.partnerTwo}</p><p className="mt-3 text-[.65rem] uppercase tracking-[.28em] text-[#9b7258]">Avec amour · Noces</p></footer>
  </main>;
}
function Portrait({src,name}:{src:string;name:string}){return <figure className="relative aspect-[4/5] overflow-hidden rounded-[2rem]"><Image src={src} alt={name} fill sizes="(max-width:640px) 100vw, 50vw" className="object-cover"/><figcaption className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-6 pb-6 pt-20 text-center serif text-4xl text-white">{name}</figcaption></figure>}
