"use server";
import { randomBytes } from "node:crypto";
import { hash } from "bcryptjs";
import { cookies } from "next/headers";
import type { Route } from "next";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requirePlatformAdmin } from "@/server/auth/authorization";
import { signOut } from "@/auth";

const idSchema=z.string().cuid();
const userSchema=z.object({firstName:z.string().trim().min(2).max(80),lastName:z.string().trim().min(2).max(80),email:z.string().trim().toLowerCase().email(),password:z.string().min(8).max(128)});
const weddingSchema=z.object({ownerId:idSchema,partnerOne:z.string().trim().min(2).max(80),partnerTwo:z.string().trim().min(2).max(80),weddingDate:z.coerce.date(),city:z.string().trim().min(2).max(100),country:z.string().trim().min(2).max(100),plan:z.enum(["FREE","ESSENTIAL","PREMIUM"]),theme:z.enum(["editorial","floral","minimal","luxury","tropical","royal"]),accentColor:z.enum(["coral","caramel","rose","sage","navy","gold","terracotta","lavender","emerald"]),siteLayout:z.enum(["editorial","cinematic","minimal","classic","split"])});
function slugify(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function go(path:string,message:string):never{redirect(`${path}?message=${encodeURIComponent(message)}` as Route)}

export async function startSupportSessionAction(formData:FormData){const admin=await requirePlatformAdmin();const parsed=z.object({weddingId:idSchema,reason:z.string().trim().min(5).max(500),duration:z.coerce.number().int().refine(value=>[15,30,60].includes(value))}).safeParse(Object.fromEntries(formData));if(!parsed.success)go("/admin/weddings","Indiquez un motif et une durée valides");const wedding=await prisma.wedding.findUnique({where:{id:parsed.data.weddingId},select:{id:true}});if(!wedding)go("/admin/weddings","Mariage introuvable");await prisma.adminSupportSession.updateMany({where:{adminId:admin.id,endedAt:null},data:{endedAt:new Date()}});const expiresAt=new Date(Date.now()+parsed.data.duration*60_000);const support=await prisma.adminSupportSession.create({data:{adminId:admin.id,weddingId:wedding.id,reason:parsed.data.reason,expiresAt}});const store=await cookies();store.delete("noces_active_wedding");store.set("noces_support_session",support.id,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",expires:expiresAt,priority:"high"});redirect("/dashboard")}
export async function clearWeddingContextAction(){const admin=await requirePlatformAdmin();const store=await cookies();const supportId=store.get("noces_support_session")?.value;if(supportId)await prisma.adminSupportSession.updateMany({where:{id:supportId,adminId:admin.id,endedAt:null},data:{endedAt:new Date()}});store.delete("noces_support_session");store.delete("noces_active_wedding");redirect("/admin" as Route)}
export async function adminLogoutAction(){await requirePlatformAdmin();await signOut({redirectTo:"/login"})}
export async function createUserAction(formData:FormData){await requirePlatformAdmin();const parsed=userSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)go("/admin/users",parsed.error.issues[0]?.message??"Informations invalides");if(await prisma.user.findUnique({where:{email:parsed.data.email},select:{id:true}}))go("/admin/users","Cette adresse e-mail existe déjà");const {password,...data}=parsed.data;await prisma.user.create({data:{...data,passwordHash:await hash(password,12)}});revalidatePath("/admin");go("/admin/users","Utilisateur créé")}
export async function updateUserStatusAction(formData:FormData){const admin=await requirePlatformAdmin();const parsed=z.object({userId:idSchema,status:z.enum(["ACTIVE","SUSPENDED"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)go("/admin/users","Action invalide");if(parsed.data.userId===admin.id)go("/admin/users","Vous ne pouvez pas suspendre votre propre compte");await prisma.user.update({where:{id:parsed.data.userId},data:{status:parsed.data.status}});revalidatePath("/admin");go("/admin/users",parsed.data.status==="ACTIVE"?"Compte activé":"Compte suspendu")}
export async function updateUserRoleAction(formData:FormData){const admin=await requirePlatformAdmin();const parsed=z.object({userId:idSchema,platformRole:z.enum(["USER","SUPER_ADMIN"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)go("/admin/users","Action invalide");if(parsed.data.userId===admin.id&&parsed.data.platformRole!=="SUPER_ADMIN")go("/admin/users","Vous ne pouvez pas retirer votre propre rôle");await prisma.user.update({where:{id:parsed.data.userId},data:{platformRole:parsed.data.platformRole}});revalidatePath("/admin");go("/admin/users","Rôle mis à jour")}
export async function deleteUserAction(formData:FormData){const admin=await requirePlatformAdmin();const id=idSchema.safeParse(formData.get("userId"));if(!id.success||id.data===admin.id)go("/admin/users","Suppression refusée");if(await prisma.weddingMember.count({where:{userId:id.data,role:"OWNER"}}))go("/admin/users","Ce compte possède un mariage : archivez ou transférez-le avant suppression");await prisma.user.delete({where:{id:id.data}});revalidatePath("/admin");go("/admin/users","Utilisateur supprimé")}
export async function createWeddingAction(formData:FormData){await requirePlatformAdmin();const parsed=weddingSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)go("/admin/weddings",parsed.error.issues[0]?.message??"Informations invalides");const owner=await prisma.user.findUnique({where:{id:parsed.data.ownerId},select:{status:true}});if(owner?.status!=="ACTIVE")go("/admin/weddings","Le propriétaire doit être un compte actif");const {ownerId,...data}=parsed.data;await prisma.wedding.create({data:{...data,slug:`${slugify(`${data.partnerOne}-${data.partnerTwo}`)}-${randomBytes(3).toString("hex")}`,members:{create:{userId:ownerId,role:"OWNER"}},groups:{create:["Famille mariée","Famille marié","Amis","Travail","VIP","Autres"].map(name=>({name}))}}});revalidatePath("/admin");go("/admin/weddings","Mariage créé")}
export async function updateWeddingAction(formData:FormData){await requirePlatformAdmin();const parsed=z.object({weddingId:idSchema,status:z.enum(["ACTIVE","SUSPENDED","ARCHIVED"]),plan:z.enum(["FREE","ESSENTIAL","PREMIUM"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)go("/admin/weddings","Action invalide");await prisma.wedding.update({where:{id:parsed.data.weddingId},data:{status:parsed.data.status,plan:parsed.data.plan}});revalidatePath("/admin");go("/admin/weddings","Mariage mis à jour")}
export async function editWeddingAction(formData:FormData){await requirePlatformAdmin();const parsed=z.object({weddingId:idSchema,partnerOne:z.string().trim().min(2).max(80),partnerTwo:z.string().trim().min(2).max(80),weddingDate:z.coerce.date(),city:z.string().trim().max(100),country:z.string().trim().max(100),theme:z.string().trim().min(2).max(40),accentColor:z.string().trim().min(2).max(40),siteLayout:z.string().trim().min(2).max(40)}).safeParse(Object.fromEntries(formData));if(!parsed.success)go("/admin/weddings",parsed.error.issues[0]?.message??"Informations invalides");const {weddingId,...data}=parsed.data;await prisma.wedding.update({where:{id:weddingId},data});revalidatePath("/admin");go("/admin/weddings","Informations et design modifiés")}
export async function deleteWeddingAction(formData:FormData){await requirePlatformAdmin();const id=idSchema.safeParse(formData.get("weddingId"));if(!id.success)go("/admin/weddings","Mariage introuvable");await prisma.wedding.delete({where:{id:id.data}});revalidatePath("/admin");go("/admin/weddings","Espace mariage supprimé")}
