import type { Metadata } from "next";
import Image from "next/image";
import { CheckCircle2,Clock3,UserX,UsersRound } from "lucide-react";
import { notFound } from "next/navigation";
import { getPublicGuestList } from "@/features/guests/public-guest-list";
type Props={params:Promise<{weddingSlug:string;token:string}>};
export const metadata:Metadata={title:"Liste des présences — Noces",robots:{index:false,follow:false}};
export default async function PublicGuestsPage({params}:Props){const{weddingSlug,token}=await params;const data=await getPublicGuestList(weddingSlug,token);if(!data)notFound();const confirmed=data.guests.filter(g=>g.status==="CONFIRMED"),declined=data.guests.filter(g=>g.status==="DECLINED"),pending=data.guests.filter(g=>g.status==="PENDING");const people=confirmed.reduce((sum,g)=>sum+g.guestCount,0);return <main className="min-h-screen bg-[#f8f3eb] text-[#49372f]"><header className="relative overflow-hidden bg-[#49372f] px-5 py-20 text-center text-white">{data.coverImageUrl&&<Image src={data.coverImageUrl} alt="" fill priority sizes="100vw" className="object-cover opacity-25"/>}<div className="relative mx-auto max-w-4xl"><p className="text-xs uppercase tracking-[.3em] text-[#e7d9c8]">Liste des présences</p><h1 className="serif mt-5 text-6xl">{data.partnerOne} <span className="italic text-[#d5b770]">&</span> {data.partnerTwo}</h1><p className="mt-5 text-sm text-white/70">{new Intl.DateTimeFormat("fr-FR",{dateStyle:"long"}).format(data.weddingDate)}{data.city?` · ${data.city}`:""}</p></div></header><div className="mx-auto max-w-6xl px-5 py-14"><section className="grid gap-4 sm:grid-cols-3"><Stat icon={CheckCircle2} label="Invitations confirmées" value={confirmed.length}/><Stat icon={UsersRound} label="Personnes attendues" value={people}/><Stat icon={Clock3} label="Réponses en attente" value={pending.length}/></section><div className="mt-10 grid gap-6 lg:grid-cols-3"><GuestColumn title="Présents" guests={confirmed} tone="green"/><GuestColumn title="Absents" guests={declined} tone="red"/><GuestColumn title="En attente" guests={pending} tone="amber"/></div><p className="mt-10 text-center text-xs text-[#9b7258]">Cette liste ne contient aucune coordonnée privée. Elle est mise à jour automatiquement avec les réponses RSVP.</p></div></main>}
function Stat({icon:Icon,label,value}:{icon:typeof CheckCircle2;label:string;value:number}){return <article className="rounded-2xl border border-[#e7d9c8] bg-white p-5"><div className="flex justify-between"><p className="text-xs text-[#9b7258]">{label}</p><Icon size={17}/></div><p className="serif mt-5 text-4xl">{value}</p></article>}
function GuestColumn({title,guests,tone}:{title:string;guests:Array<{id:string;displayName:string;guestCount:number}>;tone:"green"|"red"|"amber"}){const Icon=tone==="green"?CheckCircle2:tone==="red"?UserX:Clock3;return <section className="rounded-2xl border border-[#e7d9c8] bg-white p-5"><div className="flex items-center gap-2"><Icon size={18}/><h2 className="serif text-3xl">{title}</h2><span className="ml-auto rounded-full bg-[#f8f3eb] px-2 py-1 text-xs">{guests.length}</span></div><div className="mt-5 space-y-2">{guests.map(guest=><div key={guest.id} className="flex justify-between rounded-xl bg-[#f8f3eb] px-4 py-3 text-sm"><span>{guest.displayName}</span>{tone==="green"&&<span className="text-xs text-[#9b7258]">{guest.guestCount} pers.</span>}</div>)}{!guests.length&&<p className="py-8 text-center text-sm text-[#9b7258]">Aucun invité</p>}</div></section>}
