"use client";
import { useActionState,useState } from "react";
import { ArrowLeft,ArrowRight,Check } from "lucide-react";
import { createWeddingAction } from "@/app/onboarding/actions";
const themes=[{id:"editorial",name:"Éditorial",style:"from-[#49372f] to-[#b99d88]"},{id:"floral",name:"Floral",style:"from-[#8b6f72] to-[#eadbd0]"},{id:"minimal",name:"Minimal",style:"from-[#e7d9c8] to-white"}];
const colors=[{id:"caramel",name:"Caramel",hex:"#9b7258"},{id:"rose",name:"Rose",hex:"#b47b84"},{id:"sage",name:"Sauge",hex:"#738675"},{id:"navy",name:"Nuit",hex:"#34445c"},{id:"gold",name:"Or",hex:"#b79a45"}];
const layouts=[{id:"editorial",name:"Magazine",description:"Élégant et narratif"},{id:"cinematic",name:"Cinématique",description:"Images immersives"},{id:"minimal",name:"Essentiel",description:"Sobre et lisible"}];
export function OnboardingForm(){const[step,setStep]=useState(1);const[state,action,pending]=useActionState(createWeddingAction,{});return <form action={action} className="mx-auto w-full max-w-3xl rounded-3xl border border-[var(--beige)] bg-white p-6 shadow-xl shadow-[#49372f]/5 sm:p-10"><div className="mb-9 flex gap-2">{[1,2,3].map(item=><div key={item} className={`h-1.5 flex-1 rounded-full ${item<=step?"bg-[var(--brown)]":"bg-[var(--beige)]"}`}/>)}</div>
  <div className={step===1?"block":"hidden"}><p className="eyebrow">Étape 1 sur 3</p><h2 className="serif mt-3 text-4xl">Parlez-nous de vous</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><Field name="partnerOne" label="Prénom partenaire 1"/><Field name="partnerTwo" label="Prénom partenaire 2"/></div></div>
  <div className={step===2?"block":"hidden"}><p className="eyebrow">Étape 2 sur 3</p><h2 className="serif mt-3 text-4xl">Quand et où ?</h2><div className="mt-8 space-y-5"><Field name="weddingDate" label="Date du mariage" type="date"/><div className="grid gap-5 sm:grid-cols-2"><Field name="city" label="Ville"/><Field name="country" label="Pays"/></div></div></div>
  <div className={step===3?"block":"hidden"}><p className="eyebrow">Étape 3 sur 3</p><h2 className="serif mt-3 text-4xl">Composez votre univers</h2><p className="mt-2 text-sm text-[var(--caramel)]">Un aperçu clair plutôt qu’une liste déroulante. Ces choix restent modifiables.</p><h3 className="mt-7 text-sm font-semibold">Ambiance</h3><div className="mt-3 grid grid-cols-3 gap-3">{themes.map(theme=><label key={theme.id} className="cursor-pointer"><input className="peer sr-only" type="radio" name="theme" value={theme.id} defaultChecked={theme.id==="editorial"}/><span className="block rounded-2xl border-2 border-transparent p-2 peer-checked:border-[var(--gold)] peer-checked:bg-[var(--ivory)]"><i className={`block h-20 rounded-xl bg-gradient-to-br ${theme.style}`}/><b className="mt-2 block text-center text-sm font-medium">{theme.name}</b></span></label>)}</div><h3 className="mt-6 text-sm font-semibold">Couleur principale</h3><div className="mt-3 flex flex-wrap gap-3">{colors.map(color=><label key={color.id} className="cursor-pointer"><input className="peer sr-only" type="radio" name="accentColor" value={color.id} defaultChecked={color.id==="caramel"}/><span className="flex items-center gap-2 rounded-full border-2 border-transparent bg-[var(--ivory)] px-3 py-2 text-xs peer-checked:border-[var(--brown)]"><i className="h-5 w-5 rounded-full" style={{backgroundColor:color.hex}}/>{color.name}</span></label>)}</div><h3 className="mt-6 text-sm font-semibold">Mise en page</h3><div className="mt-3 grid gap-3 sm:grid-cols-3">{layouts.map(layout=><label key={layout.id} className="cursor-pointer"><input className="peer sr-only" type="radio" name="siteLayout" value={layout.id} defaultChecked={layout.id==="editorial"}/><span className="block rounded-xl border-2 border-[var(--beige)] p-3 peer-checked:border-[var(--brown)] peer-checked:bg-[var(--ivory)]"><strong className="block text-sm">{layout.name}</strong><small className="mt-1 block text-[var(--caramel)]">{layout.description}</small></span></label>)}</div></div>
  {state.error&&<p className="mt-6 rounded-xl bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}<div className="mt-10 flex justify-between">{step>1?<button type="button" onClick={()=>setStep(step-1)} className="button-secondary"><ArrowLeft size={16}/>Retour</button>:<span/>}{step<3?<button type="button" onClick={()=>setStep(step+1)} className="button-primary">Continuer<ArrowRight size={16}/></button>:<button disabled={pending} className="button-primary">{pending?"Création…":<>Créer mon mariage<Check size={16}/></>}</button>}</div></form>}
function Field({name,label,type="text"}:{name:string;label:string;type?:string}){return <label className="block"><span className="mb-2 block text-sm">{label}</span><input name={name} type={type} required className="w-full rounded-xl border border-[var(--beige)] px-4 py-3.5 outline-none focus:border-[var(--caramel)]"/></label>}
