"use client";
import { Save } from "lucide-react";
import { useActionState } from "react";
import { updateWeddingSettingsAction,type SettingsState } from "@/app/dashboard/settings/actions";
type Wedding={partnerOne:string;partnerTwo:string;weddingDate:string;rsvpDeadline:string|null;city:string|null;country:string|null;message:string|null;dressCode:string|null;contactPhone:string|null;theme:string;accentColor:string;siteLayout:string};const initial:SettingsState={};
const choices={theme:[["editorial","Éditorial"],["floral","Floral"],["minimal","Minimal"]],layout:[["editorial","Magazine"],["cinematic","Cinématique"],["minimal","Essentiel"]]};const colors=[["caramel","#9b7258"],["rose","#b47b84"],["sage","#738675"],["navy","#34445c"],["gold","#b79a45"]];
export function SettingsForm({wedding}:{wedding:Wedding}){const[state,action,pending]=useActionState(updateWeddingSettingsAction,initial);return <form action={action} className="rounded-2xl border border-[var(--beige)] bg-white p-6"><h2 className="serif text-3xl">Informations et apparence</h2><div className="mt-6 grid gap-5 md:grid-cols-2"><Field name="partnerOne" label="Premier marié" value={wedding.partnerOne}/><Field name="partnerTwo" label="Deuxième marié" value={wedding.partnerTwo}/><Field name="weddingDate" label="Date et heure" type="datetime-local" value={wedding.weddingDate}/><Field name="rsvpDeadline" label="Date limite RSVP" type="datetime-local" value={wedding.rsvpDeadline??""}/><Field name="city" label="Ville" value={wedding.city??""}/><Field name="country" label="Pays" value={wedding.country??""}/><Field name="dressCode" label="Dress code" value={wedding.dressCode??""}/><Field name="contactPhone" label="Téléphone" value={wedding.contactPhone??""}/><Choice title="Ambiance graphique" name="theme" value={wedding.theme} choices={choices.theme}/><fieldset className="md:col-span-2"><legend className="text-sm">Couleur principale</legend><div className="mt-3 flex gap-4">{colors.map(([value,hex])=><label key={value} className="cursor-pointer"><input className="peer sr-only" type="radio" name="accentColor" value={value} defaultChecked={wedding.accentColor===value}/><span className="block h-11 w-11 rounded-full border-4 border-white outline outline-2 outline-transparent peer-checked:outline-[var(--brown)]" style={{backgroundColor:hex}}/></label>)}</div></fieldset><Choice title="Style du mini-site" name="siteLayout" value={wedding.siteLayout} choices={choices.layout}/><label className="text-sm md:col-span-2">Message d’accueil<textarea name="message" defaultValue={wedding.message??""} rows={5} maxLength={3000} className="mt-2 w-full rounded-xl border border-[var(--beige)] px-4 py-3"/></label></div>{state.error&&<p className="mt-4 text-sm text-red-700">{state.error}</p>}{state.ok&&<p className="mt-4 text-sm text-emerald-700">Modifications enregistrées.</p>}<button disabled={pending} className="button-primary mt-6"><Save size={17}/>{pending?"Enregistrement…":"Enregistrer"}</button></form>}
function Choice({title,name,value,choices}:{title:string;name:string;value:string;choices:string[][]}){return <fieldset className="md:col-span-2"><legend className="text-sm">{title}</legend><div className="mt-3 grid gap-3 sm:grid-cols-3">{choices.map(([id,label])=><label key={id} className="cursor-pointer"><input className="peer sr-only" type="radio" name={name} value={id} defaultChecked={value===id}/><span className="block rounded-xl border-2 border-[var(--beige)] p-4 text-center peer-checked:border-[var(--brown)] peer-checked:bg-[var(--ivory)]">{label}</span></label>)}</div></fieldset>}
function Field({name,label,value,type="text"}:{name:string;label:string;value:string;type?:string}){return <label className="text-sm">{label}<input required={["partnerOne","partnerTwo","weddingDate"].includes(name)} name={name} type={type} defaultValue={value} className="mt-2 w-full rounded-xl border border-[var(--beige)] px-4 py-3"/></label>}
